# General  
finetune: True
partial_train: null

# Traning 
epochs: 30 #300
batch_size: 8 #32 
lr_backbone: 0.0001
lr_head: 0.001
weight_decay: 0.01
lr_decay: 0.99

# Model
model_version: class
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
num_joints: 17
hidden_dim: 1024 #2048
dropout_ratio: 0.5

# Data
dataset: custom_only_target_action_hrnet_modified
data_split: xsub
clip_len: 243
action_classes: 5 # test하는 모델의 action class 수와 동일하게 설정

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]