# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null
test_run: False

# Traning 
epochs: 60
checkpoint_frequency: 30
batch_size: 16
dropout: 0.0
learning_rate: 0.01
weight_decay: 0.01
lr_decay: 0.99

# Test
#part_list: ['']

# Model
model: DHDST_onevec
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: data/motion3d/MB3D_f243s81/
subset_list: [H36M-SH_S1_WITH_NO_FACTOR]
dt_file: h36m_sh_s1.pkl
clip_len: 243
data_stride: 81
rootrel: False
sample_stride: 1
num_joints: 2
no_conf: False
gt_2d: False

# DH
train_length_type: each 
test_length_type: each 
length_frame: 0 
pred_length: True

# Loss
lambda_root_point: 0.0
lambda_length: 1
lambda_angle: 1
lambda_onevec_pos: 5

# Augmentation
synthetic: False
flip: False
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
