# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null

# Traning 
epochs: 30
checkpoint_frequency: 30
batch_size: 14
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
model: DHDST2
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: data/motion3d/MB3D_f243s81/
subset_list: [KOOKMIN_TOTAL_WITH_KOOKMIN_SETTING_S0258_TEST]
dt_file: kookmin_total_with_kookmin_setting_s0258_test.pkl
clip_len: 243
data_stride: 81
rootrel: False
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False

# DH
train_length_type: each 
test_length_type: each 
length_frame: 0 
pred_length: True

# Loss
lambda_pos: 1.0
lambda_3d_velocity: 20.0
lambda_scale: 0.5
# lambda_lv: 0.0
# lambda_lg: 0.0
# lambda_a: 0.0
# lambda_av: 0.0
# lambda_sym: 10.0

# Augmentation
synthetic: False
flip: False
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
