att_fuse: true
batch_size: 16
canonical: true
checkpoint_frequency: 30
clip_len: 243
data_root: data/motion3d/MB3D_f243s81/
data_stride: 81
depth: 5
dim_feat: 512
dim_rep: 512
dropout: 0.0
dt_file: h36m_sh_conf_cam_source_final.pkl
epochs: 60
finetune: true
flip: true
gt_2d: false
lambda_3d_pos: 1.0
lambda_3d_velocity: 20.0
lambda_a: 0.0
lambda_av: 0.0
lambda_lg: 0.0
lambda_lv: 0.0
lambda_scale: 0.5
learning_rate: 0.0002
lr_decay: 0.99
mask_T_ratio: 0.0
mask_ratio: 0.0
maxlen: 243
mlp_ratio: 2
model: MB_ft_h36m_with_canonical2
no_conf: false
no_eval: false
noise: false
num_heads: 8
num_joints: 17
only_limb: false
partial_train: null
rootrel: true
sample_stride: 1
subset_list:
- H36M-SH
synthetic: false
test_run: false
train_2d: false
weight_decay: 0.01
