# General
train_2d: False
no_eval: False
finetune: False
partial_train: null
input_centering: False
test_run: False
fix_orientation_pred: True

# Traning
epochs: 60
checkpoint_frequency: 30
batch_size: 16
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99
gt_mode: cam_3d
input_mode: joint_2d_from_canonical_3d

# Test
part_list: ['whole']
denormalize_output: False

# Model
model: 'MB_train_h36m_gt_cam_no_factor_input_from_canonical_pcl'
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: data/motion3d/MB3D_f243s81/
subset_list: [H36M-GT-CAM_NO_FACTOR-INPUT_FROM_CANONICAL_PCL]
#dt_file: h36m_gt_canonical_3d_same_z_tr_s1_ts_s5678.pkl
clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False

# Loss
lambda_3d_pos: 1.0
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
