att_fuse: true
batch_size: 16
canonical: true
checkpoint_frequency: 30
clip_len: 243
data_root: data/motion3d/MB3D_f243s81/
data_stride: 81
denormalize_output: false
depth: 5
dim_feat: 512
dim_rep: 512
dropout: 0.0
#dt_file: h36m_gt_canonical_3d_same_z_tr_s1_ts_s5678.pkl
epochs: 60
finetune: false
flip: true
gt_2d: false
gt_mode: cam_3d
input_mode: joint_2d
lambda_3d_pos: 1.0
lambda_3d_velocity: 20.0
lambda_a: 0.0
lambda_av: 0.0
lambda_lg: 0.0
lambda_lv: 0.0
lambda_scale: 0.5
learning_rate: 0.0002
lr_decay: 0.99
mask_T_ratio: 0.0
mask_ratio: 0.0
maxlen: 243
mlp_ratio: 2
model: MB_train_h36m_gt_cam_no_factor_steprot_0.5_1_1.5+original_tr_s1_ts_s5678
no_conf: false
no_eval: false
noise: false
num_heads: 8
num_joints: 17
part_list:
- whole
partial_train: null
rootrel: true
sample_stride: 1
#step_rot: 1.5
subset_list:
- H36M-GT-CAM_NO_FACTOR-STEP_ROT_1.5-TR_S1_TS_S5678
- H36M-GT-CAM_NO_FACTOR-STEP_ROT_1-TR_S1_TS_S5678
- H36M-GT-CAM_NO_FACTOR-STEP_ROT_0.5-TR_S1_TS_S5678
- H36M-GT-CAM_NO_FACTOR-TR_S1_TS_S5678
synthetic: false
test_run: false
train_2d: false
weight_decay: 0.01
