ax_world_3d_xlim: [-5, 5]
ax_world_3d_ylim: [-5, 5]
ax_world_3d_zlim: [-10, 2]
ax_world_3d_view: [90, 90]
ax_cam_3d_view: [-90, -90]
ax_img_3d_view: [-90, -90]
ax_cam_scaled_xlim: [-1000, 1000]
ax_cam_scaled_ylim: [-1000, 1000]
ax_cam_scaled_zlim: [-1000, 1000]
ax_cam_scaled_view: [-90, -90]