# General  
train_2d: False
no_eval: False
finetune: False
partial_train: null
canonical: False
test_run: False

# Traning 
epochs: 60
checkpoint_frequency: 30
batch_size: 16
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Test
part_list: ['whole'] 
denormalize_output: False

# Model
backbone: 'CanonDSTformer2'
dim_in: 2
dim_out: 2
model: 'CanonDSTformer2_train_h36m_gt_tr_s1_ts_s5678_trial4'
maxlen: 243
dim_feat: 256
mlp_ratio: 2
depth: 3
dim_rep: 256
num_heads: 8
att_fuse: True

# Data
data_root: data/motion3d/MB3D_f243s81/
subset_list: [H36M_CANONICALIZATION-GT-INPUT_FROM_3D_CANONICAL_SAME_Z-TR_S1_TS_S5678]
dt_file: h36m_gt_canonical_3d_same_z_tr_s1_ts_s5678.pkl
clip_len: 243
data_stride: 81
rootrel: False
sample_stride: 1
num_joints: 17
no_conf: True
gt_2d: False
input_mode: 'joint_2d'
gt_mode: 'joint_2d_from_canonical_3d'

# Loss
lambda_3d_pos: 0.0
lambda_3d_velocity: 0.0
lambda_scale: 0.0
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0
lambda_canonical_2d_residual: 1.0

# Augmentation
synthetic: False
flip: False
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
